services: 
  app:
    build: 
      context: ../
      dockerfile: Dockerfile
    image: reno-projects-watch
    command: npm run watch
    develop:
      watch:
        - action: sync
          path: ../src
          target: /src
          ignore:
            - node_modules/
            - dist/